# NumPy tutorial

In [1]:
import numpy as np

In [2]:
import sklearn

In [3]:
myarr = np.array([[3,6,37,7]], np.int8)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype


dtype('int8')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 37,  7]], dtype=int8)

# Array Creation : Creation from other python structures

In [9]:
zeros = np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng = np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace = np.linspace(1,6,5)

In [14]:
lspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [15]:
empt = np.empty((4,6))

In [16]:
empt

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.11261706e-306, 1.42419938e-306, 7.56603881e-307],
       [8.45603441e-307, 1.42417221e-306, 1.60219306e-306,
        6.23059726e-307, 1.06811422e-306, 1.42417221e-306],
       [1.37961641e-306, 8.06612616e-308, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.11260416e-306, 1.11259940e-306,
        1.60219035e-306, 7.56598449e-307, 4.53801547e+279]])

In [17]:
empt_like = np.empty_like(lspace)

In [18]:
empt_like

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [19]:
ide = np.identity(45)

In [20]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
arr1 = np.arange(99)

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr1.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [24]:
arr1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr1 = arr1.reshape(3,33) #to change the value of arr1

In [26]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr1 = arr1.ravel() #to change back to 1D array

In [28]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar.sum(axis=0)

array([12,  8,  9])

In [33]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
ar.flat

In [36]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [37]:
ar.ndim #dimension of array

2

In [38]:
ar.size

9

In [39]:
ar.nbytes #size of array

36

In [40]:
one = np.array([1,99,5,4,3,6])

In [41]:
one.argmax() #index of max  no. in array

1

In [42]:
one.argmin()

0

In [43]:
one.argsort()  #index of array in which the will be sorted in ascending order

array([0, 4, 3, 2, 5, 1], dtype=int32)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.argmin()  #it first make this array a 1D array and than find the index of min

8

In [46]:
ar.argmax()

6

In [47]:
ar.argmax(axis=0)    #it finds the index of min in axis 0

array([2, 1, 1], dtype=int32)

In [49]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [50]:
ar.argsort(axis=0)  #it gives the index of sorted array according to axis 0 

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

In [51]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [52]:
ar2 = np.array([[0, 9, 2],
       [1, 1, 7],
       [5, 6, 0]])

In [53]:
ar+ar2

array([[ 1, 11,  5],
       [ 5,  6, 13],
       [12,  7,  0]])

In [55]:
ar.shape

(3, 3)

In [56]:
ar2.shape


(3, 3)

In [57]:
ar*ar2

array([[ 0, 18,  6],
       [ 4,  5, 42],
       [35,  6,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [59]:
ar.sum()

29

In [60]:
ar.min()

0

In [61]:
ar.max()

7

In [63]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [64]:
np.count_nonzero(ar)

8

In [65]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [66]:
import sys

In [67]:
py_ar = [0,4,55,2]

In [68]:
np_ar = np.array(py_ar)

In [69]:
sys.getsizeof(1)*len(py_ar)

56

In [70]:
np_ar.itemsize * np_ar.size #difference in size

16

In [71]:
np_ar.tolist  #to cahnge numpy array to python list

<function ndarray.tolist>